export const CHANGE_MODAL_STATE = 'CHANGE_MODAL_STATE';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const GET_BUILDINGS_REQUEST = 'GET_BUILDINGS_REQUEST';
export const GET_BUILDINGS_SUCCESS = 'GET_BUILDINGS_SUCCESS';
export const GET_BUILDINGS_FAILURE = 'GET_BUILDINGS_FAILURE';

export const GET_RESIDENTS_REQUEST = 'GET_RESIDENTS_REQUEST';
export const GET_RESIDENTS_SUCCESS = 'GET_RESIDENTS_SUCCESS';
export const GET_RESIDENTS_FAILURE = 'GET_RESIDENTS_FAILURE';

export const GET_RESIDENT_REQUEST = 'GET_RESIDENT_REQUEST';
export const GET_RESIDENT_SUCCESS = 'GET_RESIDENT_SUCCESS';
export const GET_RESIDENT_FAILURE = 'GET_RESIDENT_FAILURE';

export const MAKE_PAYMENTS_REQUEST = 'MAKE_PAYMENTS_REQUEST';
export const MAKE_PAYMENTS_SUCCESS = 'MAKE_PAYMENTS_SUCCESS';
export const MAKE_PAYMENTS_FAILURE = 'MAKE_PAYMENTS_FAILURE';

export const GET_TCOUNT_EXCEL_REQUEST = 'GET_TCOUNT_EXCEL_REQUEST';
export const GET_TCOUNT_EXCEL_SUCCESS = 'GET_TCOUNT_EXCEL_SUCCESS';
export const GET_TCOUNT_EXCEL_FAILURE = 'GET_TCOUNT_EXCEL_FAILURE';

export const SIGN_OUT = 'SIGN_OUT';
